-- T1: User-scoped composite primary keys for sync-domain tables.
--
-- Rationale: prior to this migration, every sync table used `id text primary key`
-- alongside a redundant `unique (id, owner_user_id)`. Because ids were unique
-- across the whole table, identical ids generated by two different users would
-- collide on conflict resolution, surfacing as "<entity> id <id> belongs to a
-- different owner" projection failures.
--
-- This migration recreates the eight user-scoped sync tables with a composite
-- primary key `(id, owner_user_id)` so each user owns their own keyspace, drops
-- the now-redundant id-only unique constraints, re-establishes child FKs against
-- the new composite PKs, and rewrites `sync_apply_projection_event` so that:
--   * every `on conflict (id)` becomes `on conflict (id, owner_user_id)`, and
--   * every "belongs to a different owner" exception branch is removed because
--     the cross-owner collision is impossible by construction.
--
-- The hosted DB will be wiped post-merge. `drop table cascade` is acceptable.
-- Sync metadata tables (`sync_device_ingest_state`, `sync_ingested_events`) are
-- left in place; their PKs already include `owner_user_id`.

-- -----------------------------------------------------------------------------
-- 1. Drop the eight sync entity tables (cascade removes FKs/policies/triggers
--    that depended on them; we recreate everything below).
-- -----------------------------------------------------------------------------

drop table if exists app_public.session_exercise_tags cascade;
drop table if exists app_public.exercise_tag_definitions cascade;
drop table if exists app_public.exercise_muscle_mappings cascade;
drop table if exists app_public.exercise_definitions cascade;
drop table if exists app_public.exercise_sets cascade;
drop table if exists app_public.session_exercises cascade;
drop table if exists app_public.sessions cascade;
drop table if exists app_public.gyms cascade;

-- -----------------------------------------------------------------------------
-- 2. Recreate tables with composite (id, owner_user_id) primary keys.
-- -----------------------------------------------------------------------------

create table app_public.gyms (
  id text not null,
  owner_user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name text not null check (length(btrim(name)) > 0),
  origin_scope_id text not null default 'private',
  origin_source_id text not null default 'local',
  deleted_at bigint check (deleted_at is null or deleted_at >= 0),
  created_at bigint not null check (created_at >= 0),
  updated_at bigint not null check (updated_at >= 0),
  primary key (id, owner_user_id)
);

create index gyms_owner_user_id_idx on app_public.gyms (owner_user_id);
create index gyms_name_idx on app_public.gyms (name);
create index gyms_origin_scope_id_idx on app_public.gyms (origin_scope_id);
create index gyms_deleted_at_idx on app_public.gyms (deleted_at);

create table app_public.sessions (
  id text not null,
  owner_user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  gym_id text,
  status text not null default 'draft' check (status in ('draft', 'active', 'completed')),
  started_at bigint not null check (started_at >= 0),
  completed_at bigint check (completed_at is null or completed_at >= 0),
  duration_sec integer check (duration_sec is null or duration_sec >= 0),
  deleted_at bigint check (deleted_at is null or deleted_at >= 0),
  created_at bigint not null check (created_at >= 0),
  updated_at bigint not null check (updated_at >= 0),
  primary key (id, owner_user_id),
  constraint sessions_gym_owner_fk
    foreign key (gym_id, owner_user_id)
    references app_public.gyms (id, owner_user_id)
    on delete no action
);

create index sessions_owner_user_id_idx on app_public.sessions (owner_user_id);
create index sessions_status_idx on app_public.sessions (status);
create index sessions_completed_at_idx on app_public.sessions (completed_at);
create index sessions_deleted_at_idx on app_public.sessions (deleted_at);

create table app_public.exercise_definitions (
  id text not null,
  owner_user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name text not null check (length(btrim(name)) > 0),
  deleted_at bigint check (deleted_at is null or deleted_at >= 0),
  created_at bigint not null check (created_at >= 0),
  updated_at bigint not null check (updated_at >= 0),
  primary key (id, owner_user_id)
);

create index exercise_definitions_owner_user_id_idx
  on app_public.exercise_definitions (owner_user_id);
create index exercise_definitions_name_idx
  on app_public.exercise_definitions (name);
create index exercise_definitions_deleted_at_idx
  on app_public.exercise_definitions (deleted_at);

create table app_public.session_exercises (
  id text not null,
  owner_user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  session_id text not null,
  exercise_definition_id text,
  order_index integer not null check (order_index >= 0),
  name text not null check (length(btrim(name)) > 0),
  machine_name text,
  origin_scope_id text not null default 'private',
  origin_source_id text not null default 'local',
  deleted_at bigint check (deleted_at is null or deleted_at >= 0),
  created_at bigint not null check (created_at >= 0),
  updated_at bigint not null check (updated_at >= 0),
  primary key (id, owner_user_id),
  constraint session_exercises_session_owner_fk
    foreign key (session_id, owner_user_id)
    references app_public.sessions (id, owner_user_id)
    on delete cascade
  -- NOTE: the historical exercise_definition_id FK was relaxed in
  -- 20260505213500_relax_session_exercise_definition_fk.sql so first-sync outbox
  -- events can land before the definition row arrives. We preserve that
  -- behaviour: exercise_definition_id is durable metadata, not a FK.
);

comment on column app_public.session_exercises.exercise_definition_id is
  'Durable exercise definition reference carried for history/sync metadata. The referenced definition may be seeded/local or arrive later via sync.';

create index session_exercises_owner_user_id_idx
  on app_public.session_exercises (owner_user_id);
create index session_exercises_session_id_idx
  on app_public.session_exercises (session_id);
create index session_exercises_exercise_definition_id_idx
  on app_public.session_exercises (exercise_definition_id);
create index session_exercises_deleted_at_idx
  on app_public.session_exercises (deleted_at);

create unique index session_exercises_session_order_active_unique
  on app_public.session_exercises (owner_user_id, session_id, order_index)
  where deleted_at is null;

create table app_public.exercise_sets (
  id text not null,
  owner_user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  session_exercise_id text not null,
  order_index integer not null check (order_index >= 0),
  weight_value text not null default '',
  reps_value text not null default '',
  set_type text,
  deleted_at bigint check (deleted_at is null or deleted_at >= 0),
  created_at bigint not null check (created_at >= 0),
  updated_at bigint not null check (updated_at >= 0),
  primary key (id, owner_user_id),
  constraint exercise_sets_set_type_guard
    check (set_type is null or set_type in ('warm_up', 'rir_0', 'rir_1', 'rir_2')),
  constraint exercise_sets_session_exercise_owner_fk
    foreign key (session_exercise_id, owner_user_id)
    references app_public.session_exercises (id, owner_user_id)
    on delete cascade
);

create index exercise_sets_owner_user_id_idx
  on app_public.exercise_sets (owner_user_id);
create index exercise_sets_session_exercise_id_idx
  on app_public.exercise_sets (session_exercise_id);
create index exercise_sets_deleted_at_idx
  on app_public.exercise_sets (deleted_at);

create unique index exercise_sets_session_exercise_order_active_unique
  on app_public.exercise_sets (owner_user_id, session_exercise_id, order_index)
  where deleted_at is null;

create table app_public.exercise_muscle_mappings (
  id text not null,
  owner_user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  exercise_definition_id text not null,
  muscle_group_id text not null check (length(btrim(muscle_group_id)) > 0),
  weight double precision not null check (weight > 0),
  role text check (role is null or role in ('primary', 'secondary', 'stabilizer')),
  created_at bigint not null check (created_at >= 0),
  updated_at bigint not null check (updated_at >= 0),
  primary key (id, owner_user_id),
  constraint exercise_muscle_mappings_exercise_muscle_owner_unique
    unique (exercise_definition_id, muscle_group_id, owner_user_id),
  constraint exercise_muscle_mappings_exercise_definition_owner_fk
    foreign key (exercise_definition_id, owner_user_id)
    references app_public.exercise_definitions (id, owner_user_id)
    on delete cascade
);

create index exercise_muscle_mappings_owner_user_id_idx
  on app_public.exercise_muscle_mappings (owner_user_id);
create index exercise_muscle_mappings_exercise_definition_id_idx
  on app_public.exercise_muscle_mappings (exercise_definition_id);
create index exercise_muscle_mappings_muscle_group_id_idx
  on app_public.exercise_muscle_mappings (muscle_group_id);

create table app_public.exercise_tag_definitions (
  id text not null,
  owner_user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  exercise_definition_id text not null,
  name text not null check (length(btrim(name)) > 0),
  normalized_name text not null check (length(btrim(normalized_name)) > 0),
  deleted_at bigint check (deleted_at is null or deleted_at >= 0),
  created_at bigint not null check (created_at >= 0),
  updated_at bigint not null check (updated_at >= 0),
  primary key (id, owner_user_id),
  constraint exercise_tag_definitions_exercise_id_normalized_name_owner_unique
    unique (exercise_definition_id, normalized_name, owner_user_id),
  constraint exercise_tag_definitions_exercise_definition_owner_fk
    foreign key (exercise_definition_id, owner_user_id)
    references app_public.exercise_definitions (id, owner_user_id)
    on delete cascade
);

create index exercise_tag_definitions_owner_user_id_idx
  on app_public.exercise_tag_definitions (owner_user_id);
create index exercise_tag_definitions_exercise_definition_id_idx
  on app_public.exercise_tag_definitions (exercise_definition_id);
create index exercise_tag_definitions_deleted_at_idx
  on app_public.exercise_tag_definitions (deleted_at);

create table app_public.session_exercise_tags (
  id text not null,
  owner_user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  session_exercise_id text not null,
  exercise_tag_definition_id text not null,
  created_at bigint not null check (created_at >= 0),
  primary key (id, owner_user_id),
  constraint session_exercise_tags_session_exercise_tag_owner_unique
    unique (session_exercise_id, exercise_tag_definition_id, owner_user_id),
  constraint session_exercise_tags_session_exercise_owner_fk
    foreign key (session_exercise_id, owner_user_id)
    references app_public.session_exercises (id, owner_user_id)
    on delete cascade,
  constraint session_exercise_tags_exercise_tag_definition_owner_fk
    foreign key (exercise_tag_definition_id, owner_user_id)
    references app_public.exercise_tag_definitions (id, owner_user_id)
    on delete cascade
);

create index session_exercise_tags_owner_user_id_idx
  on app_public.session_exercise_tags (owner_user_id);
create index session_exercise_tags_session_exercise_id_idx
  on app_public.session_exercise_tags (session_exercise_id);
create index session_exercise_tags_exercise_tag_definition_id_idx
  on app_public.session_exercise_tags (exercise_tag_definition_id);

-- -----------------------------------------------------------------------------
-- 3. Grants (mirror M5/M13 grants for the recreated tables).
-- -----------------------------------------------------------------------------

grant select, insert, update, delete on table app_public.gyms to authenticated;
grant select, insert, update, delete on table app_public.sessions to authenticated;
grant select, insert, update, delete on table app_public.session_exercises to authenticated;
grant select, insert, update, delete on table app_public.exercise_sets to authenticated;
grant select, insert, update, delete on table app_public.exercise_definitions to authenticated;
grant select, insert, update, delete on table app_public.exercise_muscle_mappings to authenticated;
grant select, insert, update, delete on table app_public.exercise_tag_definitions to authenticated;
grant select, insert, update, delete on table app_public.session_exercise_tags to authenticated;

grant select, insert, update, delete on table app_public.gyms to service_role;
grant select, insert, update, delete on table app_public.sessions to service_role;
grant select, insert, update, delete on table app_public.session_exercises to service_role;
grant select, insert, update, delete on table app_public.exercise_sets to service_role;
grant select, insert, update, delete on table app_public.exercise_definitions to service_role;
grant select, insert, update, delete on table app_public.exercise_muscle_mappings to service_role;
grant select, insert, update, delete on table app_public.exercise_tag_definitions to service_role;
grant select, insert, update, delete on table app_public.session_exercise_tags to service_role;

-- -----------------------------------------------------------------------------
-- 4. Re-attach owner_user_id immutability triggers.
-- -----------------------------------------------------------------------------

drop trigger if exists gyms_owner_user_id_immutable on app_public.gyms;
create trigger gyms_owner_user_id_immutable
before update on app_public.gyms
for each row
execute function app_public.enforce_owner_user_id_immutable();

drop trigger if exists sessions_owner_user_id_immutable on app_public.sessions;
create trigger sessions_owner_user_id_immutable
before update on app_public.sessions
for each row
execute function app_public.enforce_owner_user_id_immutable();

drop trigger if exists session_exercises_owner_user_id_immutable on app_public.session_exercises;
create trigger session_exercises_owner_user_id_immutable
before update on app_public.session_exercises
for each row
execute function app_public.enforce_owner_user_id_immutable();

drop trigger if exists exercise_sets_owner_user_id_immutable on app_public.exercise_sets;
create trigger exercise_sets_owner_user_id_immutable
before update on app_public.exercise_sets
for each row
execute function app_public.enforce_owner_user_id_immutable();

drop trigger if exists exercise_definitions_owner_user_id_immutable on app_public.exercise_definitions;
create trigger exercise_definitions_owner_user_id_immutable
before update on app_public.exercise_definitions
for each row
execute function app_public.enforce_owner_user_id_immutable();

drop trigger if exists exercise_muscle_mappings_owner_user_id_immutable on app_public.exercise_muscle_mappings;
create trigger exercise_muscle_mappings_owner_user_id_immutable
before update on app_public.exercise_muscle_mappings
for each row
execute function app_public.enforce_owner_user_id_immutable();

drop trigger if exists exercise_tag_definitions_owner_user_id_immutable on app_public.exercise_tag_definitions;
create trigger exercise_tag_definitions_owner_user_id_immutable
before update on app_public.exercise_tag_definitions
for each row
execute function app_public.enforce_owner_user_id_immutable();

drop trigger if exists session_exercise_tags_owner_user_id_immutable on app_public.session_exercise_tags;
create trigger session_exercise_tags_owner_user_id_immutable
before update on app_public.session_exercise_tags
for each row
execute function app_public.enforce_owner_user_id_immutable();

-- -----------------------------------------------------------------------------
-- 5. Re-enable RLS and re-create owner-scoped policies.
-- -----------------------------------------------------------------------------

alter table app_public.gyms enable row level security;
alter table app_public.sessions enable row level security;
alter table app_public.session_exercises enable row level security;
alter table app_public.exercise_sets enable row level security;
alter table app_public.exercise_definitions enable row level security;
alter table app_public.exercise_muscle_mappings enable row level security;
alter table app_public.exercise_tag_definitions enable row level security;
alter table app_public.session_exercise_tags enable row level security;

drop policy if exists gyms_owner_select on app_public.gyms;
create policy gyms_owner_select on app_public.gyms
  for select to authenticated using (owner_user_id = auth.uid());
drop policy if exists gyms_owner_insert on app_public.gyms;
create policy gyms_owner_insert on app_public.gyms
  for insert to authenticated with check (owner_user_id = auth.uid());
drop policy if exists gyms_owner_update on app_public.gyms;
create policy gyms_owner_update on app_public.gyms
  for update to authenticated
  using (owner_user_id = auth.uid()) with check (owner_user_id = auth.uid());
drop policy if exists gyms_owner_delete on app_public.gyms;
create policy gyms_owner_delete on app_public.gyms
  for delete to authenticated using (owner_user_id = auth.uid());

drop policy if exists sessions_owner_select on app_public.sessions;
create policy sessions_owner_select on app_public.sessions
  for select to authenticated using (owner_user_id = auth.uid());
drop policy if exists sessions_owner_insert on app_public.sessions;
create policy sessions_owner_insert on app_public.sessions
  for insert to authenticated with check (owner_user_id = auth.uid());
drop policy if exists sessions_owner_update on app_public.sessions;
create policy sessions_owner_update on app_public.sessions
  for update to authenticated
  using (owner_user_id = auth.uid()) with check (owner_user_id = auth.uid());
drop policy if exists sessions_owner_delete on app_public.sessions;
create policy sessions_owner_delete on app_public.sessions
  for delete to authenticated using (owner_user_id = auth.uid());

drop policy if exists session_exercises_owner_select on app_public.session_exercises;
create policy session_exercises_owner_select on app_public.session_exercises
  for select to authenticated using (owner_user_id = auth.uid());
drop policy if exists session_exercises_owner_insert on app_public.session_exercises;
create policy session_exercises_owner_insert on app_public.session_exercises
  for insert to authenticated with check (owner_user_id = auth.uid());
drop policy if exists session_exercises_owner_update on app_public.session_exercises;
create policy session_exercises_owner_update on app_public.session_exercises
  for update to authenticated
  using (owner_user_id = auth.uid()) with check (owner_user_id = auth.uid());
drop policy if exists session_exercises_owner_delete on app_public.session_exercises;
create policy session_exercises_owner_delete on app_public.session_exercises
  for delete to authenticated using (owner_user_id = auth.uid());

drop policy if exists exercise_sets_owner_select on app_public.exercise_sets;
create policy exercise_sets_owner_select on app_public.exercise_sets
  for select to authenticated using (owner_user_id = auth.uid());
drop policy if exists exercise_sets_owner_insert on app_public.exercise_sets;
create policy exercise_sets_owner_insert on app_public.exercise_sets
  for insert to authenticated with check (owner_user_id = auth.uid());
drop policy if exists exercise_sets_owner_update on app_public.exercise_sets;
create policy exercise_sets_owner_update on app_public.exercise_sets
  for update to authenticated
  using (owner_user_id = auth.uid()) with check (owner_user_id = auth.uid());
drop policy if exists exercise_sets_owner_delete on app_public.exercise_sets;
create policy exercise_sets_owner_delete on app_public.exercise_sets
  for delete to authenticated using (owner_user_id = auth.uid());

drop policy if exists exercise_definitions_owner_select on app_public.exercise_definitions;
create policy exercise_definitions_owner_select on app_public.exercise_definitions
  for select to authenticated using (owner_user_id = auth.uid());
drop policy if exists exercise_definitions_owner_insert on app_public.exercise_definitions;
create policy exercise_definitions_owner_insert on app_public.exercise_definitions
  for insert to authenticated with check (owner_user_id = auth.uid());
drop policy if exists exercise_definitions_owner_update on app_public.exercise_definitions;
create policy exercise_definitions_owner_update on app_public.exercise_definitions
  for update to authenticated
  using (owner_user_id = auth.uid()) with check (owner_user_id = auth.uid());
drop policy if exists exercise_definitions_owner_delete on app_public.exercise_definitions;
create policy exercise_definitions_owner_delete on app_public.exercise_definitions
  for delete to authenticated using (owner_user_id = auth.uid());

drop policy if exists exercise_muscle_mappings_owner_select on app_public.exercise_muscle_mappings;
create policy exercise_muscle_mappings_owner_select on app_public.exercise_muscle_mappings
  for select to authenticated using (owner_user_id = auth.uid());
drop policy if exists exercise_muscle_mappings_owner_insert on app_public.exercise_muscle_mappings;
create policy exercise_muscle_mappings_owner_insert on app_public.exercise_muscle_mappings
  for insert to authenticated with check (owner_user_id = auth.uid());
drop policy if exists exercise_muscle_mappings_owner_update on app_public.exercise_muscle_mappings;
create policy exercise_muscle_mappings_owner_update on app_public.exercise_muscle_mappings
  for update to authenticated
  using (owner_user_id = auth.uid()) with check (owner_user_id = auth.uid());
drop policy if exists exercise_muscle_mappings_owner_delete on app_public.exercise_muscle_mappings;
create policy exercise_muscle_mappings_owner_delete on app_public.exercise_muscle_mappings
  for delete to authenticated using (owner_user_id = auth.uid());

drop policy if exists exercise_tag_definitions_owner_select on app_public.exercise_tag_definitions;
create policy exercise_tag_definitions_owner_select on app_public.exercise_tag_definitions
  for select to authenticated using (owner_user_id = auth.uid());
drop policy if exists exercise_tag_definitions_owner_insert on app_public.exercise_tag_definitions;
create policy exercise_tag_definitions_owner_insert on app_public.exercise_tag_definitions
  for insert to authenticated with check (owner_user_id = auth.uid());
drop policy if exists exercise_tag_definitions_owner_update on app_public.exercise_tag_definitions;
create policy exercise_tag_definitions_owner_update on app_public.exercise_tag_definitions
  for update to authenticated
  using (owner_user_id = auth.uid()) with check (owner_user_id = auth.uid());
drop policy if exists exercise_tag_definitions_owner_delete on app_public.exercise_tag_definitions;
create policy exercise_tag_definitions_owner_delete on app_public.exercise_tag_definitions
  for delete to authenticated using (owner_user_id = auth.uid());

drop policy if exists session_exercise_tags_owner_select on app_public.session_exercise_tags;
create policy session_exercise_tags_owner_select on app_public.session_exercise_tags
  for select to authenticated using (owner_user_id = auth.uid());
drop policy if exists session_exercise_tags_owner_insert on app_public.session_exercise_tags;
create policy session_exercise_tags_owner_insert on app_public.session_exercise_tags
  for insert to authenticated with check (owner_user_id = auth.uid());
drop policy if exists session_exercise_tags_owner_update on app_public.session_exercise_tags;
create policy session_exercise_tags_owner_update on app_public.session_exercise_tags
  for update to authenticated
  using (owner_user_id = auth.uid()) with check (owner_user_id = auth.uid());
drop policy if exists session_exercise_tags_owner_delete on app_public.session_exercise_tags;
create policy session_exercise_tags_owner_delete on app_public.session_exercise_tags
  for delete to authenticated using (owner_user_id = auth.uid());

-- -----------------------------------------------------------------------------
-- 6. Rewrite sync_apply_projection_event.
--    Copied verbatim from M14 with two changes:
--      (a) every `on conflict (id)` becomes `on conflict (id, owner_user_id)`
--      (b) every "belongs to a different owner" branch is removed (cross-owner
--          collisions are now impossible by construction).
-- -----------------------------------------------------------------------------

create or replace function app_public.sync_apply_projection_event(
  p_owner_user_id uuid,
  p_entity_type text,
  p_entity_id text,
  p_event_type text,
  p_occurred_at_ms bigint,
  p_payload jsonb
)
returns void
language plpgsql
set search_path = app_public, public, extensions
as $$
declare
  v_row_count bigint;
  v_id text;
  v_name text;
  v_origin_scope_id text;
  v_origin_source_id text;
  v_gym_id text;
  v_status text;
  v_started_at_ms bigint;
  v_completed_at_ms bigint;
  v_duration_sec integer;
  v_deleted_at_ms bigint;
  v_created_at_ms bigint;
  v_updated_at_ms bigint;
  v_session_id text;
  v_session_exercise_id text;
  v_exercise_definition_id text;
  v_order_index integer;
  v_machine_name text;
  v_weight_value text;
  v_reps_value text;
  v_set_type text;
  v_normalized_name text;
  v_row_id text;
  v_muscle_group_id text;
  v_weight double precision;
  v_role text;
  v_exercise_tag_definition_id text;
begin
  if p_owner_user_id is null then
    raise exception 'owner_user_id is required' using errcode = '22023';
  end if;

  if jsonb_typeof(p_payload) <> 'object' then
    raise exception 'payload must be an object' using errcode = '22023';
  end if;

  case p_entity_type
    when 'gyms' then
      if not (p_payload ? 'id') then
        raise exception 'payload.id is required for gyms events' using errcode = '22023';
      end if;

      v_id := btrim(p_payload ->> 'id');
      if v_id = '' or v_id <> p_entity_id then
        raise exception 'payload.id must match entity_id for gyms events' using errcode = '22023';
      end if;

      if p_event_type = 'upsert' then
        v_name := p_payload ->> 'name';
        v_origin_scope_id := coalesce(p_payload ->> 'origin_scope_id', 'private');
        v_origin_source_id := coalesce(p_payload ->> 'origin_source_id', 'local');
        v_created_at_ms := (p_payload ->> 'created_at_ms')::bigint;
        v_updated_at_ms := (p_payload ->> 'updated_at_ms')::bigint;

        if length(btrim(v_name)) = 0 then
          raise exception 'payload.name is required for gyms upsert' using errcode = '22023';
        end if;

        if v_created_at_ms < 0 or v_updated_at_ms < 0 then
          raise exception 'created_at_ms and updated_at_ms must be >= 0' using errcode = '22023';
        end if;

        insert into app_public.gyms (
          id,
          owner_user_id,
          name,
          origin_scope_id,
          origin_source_id,
          deleted_at,
          created_at,
          updated_at
        )
        values (
          v_id,
          p_owner_user_id,
          v_name,
          v_origin_scope_id,
          v_origin_source_id,
          null,
          v_created_at_ms,
          v_updated_at_ms
        )
        on conflict (id, owner_user_id)
        do update
          set name = excluded.name,
              origin_scope_id = excluded.origin_scope_id,
              origin_source_id = excluded.origin_source_id,
              deleted_at = null,
              created_at = least(app_public.gyms.created_at, excluded.created_at),
              updated_at = greatest(app_public.gyms.updated_at, excluded.updated_at);
      elsif p_event_type = 'delete' then
        v_deleted_at_ms := coalesce((p_payload ->> 'deleted_at_ms')::bigint, p_occurred_at_ms);
        v_updated_at_ms := coalesce((p_payload ->> 'updated_at_ms')::bigint, v_deleted_at_ms);

        update app_public.gyms
          set deleted_at = v_deleted_at_ms,
              updated_at = greatest(updated_at, v_updated_at_ms)
          where id = v_id
            and owner_user_id = p_owner_user_id;

        get diagnostics v_row_count = row_count;
        if v_row_count = 0 then
          raise exception 'cannot delete missing gym %', v_id using errcode = 'P0002';
        end if;
      else
        raise exception 'unsupported gyms event_type: %', p_event_type using errcode = '22023';
      end if;

    when 'sessions' then
      if not (p_payload ? 'id') then
        raise exception 'payload.id is required for sessions events' using errcode = '22023';
      end if;

      v_id := btrim(p_payload ->> 'id');
      if v_id = '' or v_id <> p_entity_id then
        raise exception 'payload.id must match entity_id for sessions events' using errcode = '22023';
      end if;

      if p_event_type = 'upsert' then
        v_gym_id := nullif(btrim(coalesce(p_payload ->> 'gym_id', '')), '');
        v_status := p_payload ->> 'status';
        v_started_at_ms := (p_payload ->> 'started_at_ms')::bigint;
        v_completed_at_ms := (p_payload ->> 'completed_at_ms')::bigint;
        v_duration_sec := (p_payload ->> 'duration_sec')::integer;
        v_deleted_at_ms := (p_payload ->> 'deleted_at_ms')::bigint;
        v_created_at_ms := (p_payload ->> 'created_at_ms')::bigint;
        v_updated_at_ms := (p_payload ->> 'updated_at_ms')::bigint;

        if v_status not in ('draft', 'active', 'completed') then
          raise exception 'payload.status must be draft|active|completed for sessions upsert' using errcode = '22023';
        end if;

        if v_started_at_ms < 0 or coalesce(v_completed_at_ms, 0) < 0 or coalesce(v_deleted_at_ms, 0) < 0 then
          raise exception 'session timestamps must be >= 0' using errcode = '22023';
        end if;

        if v_created_at_ms < 0 or v_updated_at_ms < 0 then
          raise exception 'created_at_ms and updated_at_ms must be >= 0' using errcode = '22023';
        end if;

        if v_duration_sec is not null and v_duration_sec < 0 then
          raise exception 'duration_sec must be >= 0' using errcode = '22023';
        end if;

        insert into app_public.sessions (
          id,
          owner_user_id,
          gym_id,
          status,
          started_at,
          completed_at,
          duration_sec,
          deleted_at,
          created_at,
          updated_at
        )
        values (
          v_id,
          p_owner_user_id,
          v_gym_id,
          v_status,
          v_started_at_ms,
          v_completed_at_ms,
          v_duration_sec,
          v_deleted_at_ms,
          v_created_at_ms,
          v_updated_at_ms
        )
        on conflict (id, owner_user_id)
        do update
          set gym_id = excluded.gym_id,
              status = excluded.status,
              started_at = excluded.started_at,
              completed_at = excluded.completed_at,
              duration_sec = excluded.duration_sec,
              deleted_at = excluded.deleted_at,
              created_at = least(app_public.sessions.created_at, excluded.created_at),
              updated_at = greatest(app_public.sessions.updated_at, excluded.updated_at);
      elsif p_event_type = 'delete' then
        v_deleted_at_ms := coalesce((p_payload ->> 'deleted_at_ms')::bigint, p_occurred_at_ms);
        v_updated_at_ms := coalesce((p_payload ->> 'updated_at_ms')::bigint, v_deleted_at_ms);

        update app_public.sessions
          set deleted_at = v_deleted_at_ms,
              updated_at = greatest(updated_at, v_updated_at_ms)
          where id = v_id
            and owner_user_id = p_owner_user_id;

        get diagnostics v_row_count = row_count;
        if v_row_count = 0 then
          raise exception 'cannot delete missing session %', v_id using errcode = 'P0002';
        end if;
      elsif p_event_type = 'complete' then
        v_completed_at_ms := (p_payload ->> 'completed_at_ms')::bigint;
        v_duration_sec := (p_payload ->> 'duration_sec')::integer;
        v_updated_at_ms := (p_payload ->> 'updated_at_ms')::bigint;

        if v_completed_at_ms < 0 or v_duration_sec < 0 or v_updated_at_ms < 0 then
          raise exception 'completed_at_ms, duration_sec, and updated_at_ms must be >= 0' using errcode = '22023';
        end if;

        update app_public.sessions
          set status = 'completed',
              completed_at = v_completed_at_ms,
              duration_sec = v_duration_sec,
              updated_at = greatest(updated_at, v_updated_at_ms)
          where id = v_id
            and owner_user_id = p_owner_user_id;

        get diagnostics v_row_count = row_count;
        if v_row_count = 0 then
          raise exception 'cannot complete missing session %', v_id using errcode = 'P0002';
        end if;
      else
        raise exception 'unsupported sessions event_type: %', p_event_type using errcode = '22023';
      end if;

    when 'session_exercises' then
      if not (p_payload ? 'id') and p_event_type <> 'reorder' then
        raise exception 'payload.id is required for session_exercises events' using errcode = '22023';
      end if;

      if p_event_type = 'upsert' then
        v_id := btrim(p_payload ->> 'id');
        if v_id = '' or v_id <> p_entity_id then
          raise exception 'payload.id must match entity_id for session_exercises upsert' using errcode = '22023';
        end if;

        v_session_id := btrim(p_payload ->> 'session_id');
        v_exercise_definition_id := btrim(p_payload ->> 'exercise_definition_id');
        v_order_index := (p_payload ->> 'order_index')::integer;
        v_name := p_payload ->> 'name';
        v_machine_name := p_payload ->> 'machine_name';
        v_origin_scope_id := coalesce(p_payload ->> 'origin_scope_id', 'private');
        v_origin_source_id := coalesce(p_payload ->> 'origin_source_id', 'local');
        v_created_at_ms := (p_payload ->> 'created_at_ms')::bigint;
        v_updated_at_ms := (p_payload ->> 'updated_at_ms')::bigint;

        if v_session_id = '' or v_exercise_definition_id = '' then
          raise exception 'session_id and exercise_definition_id are required for session_exercises upsert' using errcode = '22023';
        end if;

        if length(btrim(v_name)) = 0 then
          raise exception 'payload.name is required for session_exercises upsert' using errcode = '22023';
        end if;

        if v_order_index < 0 or v_created_at_ms < 0 or v_updated_at_ms < 0 then
          raise exception 'order_index, created_at_ms, and updated_at_ms must be >= 0' using errcode = '22023';
        end if;

        update app_public.session_exercises
          set deleted_at = coalesce(deleted_at, v_updated_at_ms),
              updated_at = greatest(updated_at, v_updated_at_ms)
          where owner_user_id = p_owner_user_id
            and session_id = v_session_id
            and order_index = v_order_index
            and id <> v_id
            and deleted_at is null;

        insert into app_public.session_exercises (
          id,
          owner_user_id,
          session_id,
          exercise_definition_id,
          order_index,
          name,
          machine_name,
          origin_scope_id,
          origin_source_id,
          deleted_at,
          created_at,
          updated_at
        )
        values (
          v_id,
          p_owner_user_id,
          v_session_id,
          v_exercise_definition_id,
          v_order_index,
          v_name,
          nullif(v_machine_name, ''),
          v_origin_scope_id,
          v_origin_source_id,
          null,
          v_created_at_ms,
          v_updated_at_ms
        )
        on conflict (id, owner_user_id)
        do update
          set session_id = excluded.session_id,
              exercise_definition_id = excluded.exercise_definition_id,
              order_index = excluded.order_index,
              name = excluded.name,
              machine_name = excluded.machine_name,
              origin_scope_id = excluded.origin_scope_id,
              origin_source_id = excluded.origin_source_id,
              deleted_at = null,
              created_at = least(app_public.session_exercises.created_at, excluded.created_at),
              updated_at = greatest(app_public.session_exercises.updated_at, excluded.updated_at);
      elsif p_event_type = 'delete' then
        v_id := btrim(p_payload ->> 'id');
        if v_id = '' or v_id <> p_entity_id then
          raise exception 'payload.id must match entity_id for session_exercises delete' using errcode = '22023';
        end if;

        v_deleted_at_ms := coalesce((p_payload ->> 'deleted_at_ms')::bigint, p_occurred_at_ms);
        v_updated_at_ms := coalesce((p_payload ->> 'updated_at_ms')::bigint, v_deleted_at_ms);

        update app_public.session_exercises
          set deleted_at = v_deleted_at_ms,
              updated_at = greatest(updated_at, v_updated_at_ms)
          where id = v_id
            and owner_user_id = p_owner_user_id;

        get diagnostics v_row_count = row_count;
        if v_row_count = 0 then
          raise exception 'cannot delete missing session_exercise %', v_id using errcode = 'P0002';
        end if;
      elsif p_event_type = 'reorder' then
        v_id := p_entity_id;
        v_session_id := btrim(p_payload ->> 'session_id');
        v_order_index := (p_payload ->> 'order_index')::integer;
        v_updated_at_ms := coalesce((p_payload ->> 'updated_at_ms')::bigint, p_occurred_at_ms);

        if v_id = '' or v_session_id = '' then
          raise exception 'entity_id and payload.session_id are required for session_exercises reorder' using errcode = '22023';
        end if;

        if v_order_index < 0 or v_updated_at_ms < 0 then
          raise exception 'order_index and updated_at_ms must be >= 0' using errcode = '22023';
        end if;

        update app_public.session_exercises
          set deleted_at = coalesce(deleted_at, v_updated_at_ms),
              updated_at = greatest(updated_at, v_updated_at_ms)
          where owner_user_id = p_owner_user_id
            and session_id = v_session_id
            and order_index = v_order_index
            and id <> v_id
            and deleted_at is null;

        update app_public.session_exercises
          set session_id = v_session_id,
              order_index = v_order_index,
              deleted_at = null,
              updated_at = greatest(updated_at, v_updated_at_ms)
          where id = v_id
            and owner_user_id = p_owner_user_id;

        get diagnostics v_row_count = row_count;
        if v_row_count = 0 then
          raise exception 'cannot reorder missing session_exercise %', v_id using errcode = 'P0002';
        end if;
      else
        raise exception 'unsupported session_exercises event_type: %', p_event_type using errcode = '22023';
      end if;

    when 'exercise_sets' then
      if not (p_payload ? 'id') and p_event_type <> 'reorder' then
        raise exception 'payload.id is required for exercise_sets events' using errcode = '22023';
      end if;

      if p_event_type = 'upsert' then
        v_id := btrim(p_payload ->> 'id');
        if v_id = '' or v_id <> p_entity_id then
          raise exception 'payload.id must match entity_id for exercise_sets upsert' using errcode = '22023';
        end if;

        v_session_exercise_id := btrim(p_payload ->> 'session_exercise_id');
        v_order_index := (p_payload ->> 'order_index')::integer;
        v_weight_value := coalesce(p_payload ->> 'weight_value', '');
        v_reps_value := coalesce(p_payload ->> 'reps_value', '');
        v_set_type := nullif(btrim(coalesce(p_payload ->> 'set_type', '')), '');
        v_created_at_ms := (p_payload ->> 'created_at_ms')::bigint;
        v_updated_at_ms := (p_payload ->> 'updated_at_ms')::bigint;

        if v_session_exercise_id = '' then
          raise exception 'payload.session_exercise_id is required for exercise_sets upsert' using errcode = '22023';
        end if;

        if v_order_index < 0 or v_created_at_ms < 0 or v_updated_at_ms < 0 then
          raise exception 'order_index, created_at_ms, and updated_at_ms must be >= 0' using errcode = '22023';
        end if;

        if v_set_type is not null and v_set_type not in ('warm_up', 'rir_0', 'rir_1', 'rir_2') then
          raise exception 'payload.set_type must be warm_up|rir_0|rir_1|rir_2|null for exercise_sets upsert' using errcode = '22023';
        end if;

        update app_public.exercise_sets
          set deleted_at = coalesce(deleted_at, v_updated_at_ms),
              updated_at = greatest(updated_at, v_updated_at_ms)
          where owner_user_id = p_owner_user_id
            and session_exercise_id = v_session_exercise_id
            and order_index = v_order_index
            and id <> v_id
            and deleted_at is null;

        insert into app_public.exercise_sets (
          id,
          owner_user_id,
          session_exercise_id,
          order_index,
          weight_value,
          reps_value,
          set_type,
          deleted_at,
          created_at,
          updated_at
        )
        values (
          v_id,
          p_owner_user_id,
          v_session_exercise_id,
          v_order_index,
          v_weight_value,
          v_reps_value,
          v_set_type,
          null,
          v_created_at_ms,
          v_updated_at_ms
        )
        on conflict (id, owner_user_id)
        do update
          set session_exercise_id = excluded.session_exercise_id,
              order_index = excluded.order_index,
              weight_value = excluded.weight_value,
              reps_value = excluded.reps_value,
              set_type = excluded.set_type,
              deleted_at = null,
              created_at = least(app_public.exercise_sets.created_at, excluded.created_at),
              updated_at = greatest(app_public.exercise_sets.updated_at, excluded.updated_at);
      elsif p_event_type = 'delete' then
        v_id := btrim(p_payload ->> 'id');
        if v_id = '' or v_id <> p_entity_id then
          raise exception 'payload.id must match entity_id for exercise_sets delete' using errcode = '22023';
        end if;

        v_deleted_at_ms := coalesce((p_payload ->> 'deleted_at_ms')::bigint, p_occurred_at_ms);
        v_updated_at_ms := coalesce((p_payload ->> 'updated_at_ms')::bigint, v_deleted_at_ms);

        update app_public.exercise_sets
          set deleted_at = v_deleted_at_ms,
              updated_at = greatest(updated_at, v_updated_at_ms)
          where id = v_id
            and owner_user_id = p_owner_user_id;

        get diagnostics v_row_count = row_count;
        if v_row_count = 0 then
          raise exception 'cannot delete missing exercise_set %', v_id using errcode = 'P0002';
        end if;
      elsif p_event_type = 'reorder' then
        v_id := p_entity_id;
        v_session_exercise_id := btrim(p_payload ->> 'session_exercise_id');
        v_order_index := (p_payload ->> 'order_index')::integer;
        v_updated_at_ms := coalesce((p_payload ->> 'updated_at_ms')::bigint, p_occurred_at_ms);

        if v_id = '' or v_session_exercise_id = '' then
          raise exception 'entity_id and payload.session_exercise_id are required for exercise_sets reorder' using errcode = '22023';
        end if;

        if v_order_index < 0 or v_updated_at_ms < 0 then
          raise exception 'order_index and updated_at_ms must be >= 0' using errcode = '22023';
        end if;

        update app_public.exercise_sets
          set deleted_at = coalesce(deleted_at, v_updated_at_ms),
              updated_at = greatest(updated_at, v_updated_at_ms)
          where owner_user_id = p_owner_user_id
            and session_exercise_id = v_session_exercise_id
            and order_index = v_order_index
            and id <> v_id
            and deleted_at is null;

        update app_public.exercise_sets
          set session_exercise_id = v_session_exercise_id,
              order_index = v_order_index,
              deleted_at = null,
              updated_at = greatest(updated_at, v_updated_at_ms)
          where id = v_id
            and owner_user_id = p_owner_user_id;

        get diagnostics v_row_count = row_count;
        if v_row_count = 0 then
          raise exception 'cannot reorder missing exercise_set %', v_id using errcode = 'P0002';
        end if;
      else
        raise exception 'unsupported exercise_sets event_type: %', p_event_type using errcode = '22023';
      end if;

    when 'exercise_definitions' then
      if not (p_payload ? 'id') then
        raise exception 'payload.id is required for exercise_definitions events' using errcode = '22023';
      end if;

      v_id := btrim(p_payload ->> 'id');
      if v_id = '' or v_id <> p_entity_id then
        raise exception 'payload.id must match entity_id for exercise_definitions events' using errcode = '22023';
      end if;

      if p_event_type = 'upsert' then
        v_name := p_payload ->> 'name';
        v_deleted_at_ms := (p_payload ->> 'deleted_at_ms')::bigint;
        v_created_at_ms := (p_payload ->> 'created_at_ms')::bigint;
        v_updated_at_ms := (p_payload ->> 'updated_at_ms')::bigint;

        if length(btrim(v_name)) = 0 then
          raise exception 'payload.name is required for exercise_definitions upsert' using errcode = '22023';
        end if;

        if v_created_at_ms < 0 or v_updated_at_ms < 0 or coalesce(v_deleted_at_ms, 0) < 0 then
          raise exception 'exercise_definitions timestamps must be >= 0' using errcode = '22023';
        end if;

        insert into app_public.exercise_definitions (
          id,
          owner_user_id,
          name,
          deleted_at,
          created_at,
          updated_at
        )
        values (
          v_id,
          p_owner_user_id,
          v_name,
          v_deleted_at_ms,
          v_created_at_ms,
          v_updated_at_ms
        )
        on conflict (id, owner_user_id)
        do update
          set name = excluded.name,
              deleted_at = excluded.deleted_at,
              created_at = least(app_public.exercise_definitions.created_at, excluded.created_at),
              updated_at = greatest(app_public.exercise_definitions.updated_at, excluded.updated_at);
      elsif p_event_type = 'delete' then
        v_deleted_at_ms := coalesce((p_payload ->> 'deleted_at_ms')::bigint, p_occurred_at_ms);
        v_updated_at_ms := coalesce((p_payload ->> 'updated_at_ms')::bigint, v_deleted_at_ms);

        update app_public.exercise_definitions
          set deleted_at = v_deleted_at_ms,
              updated_at = greatest(updated_at, v_updated_at_ms)
          where id = v_id
            and owner_user_id = p_owner_user_id;

        get diagnostics v_row_count = row_count;
        if v_row_count = 0 then
          raise exception 'cannot delete missing exercise_definition %', v_id using errcode = 'P0002';
        end if;
      else
        raise exception 'unsupported exercise_definitions event_type: %', p_event_type using errcode = '22023';
      end if;

    when 'exercise_muscle_mappings' then
      if p_event_type = 'attach' then
        v_row_id := btrim(p_payload ->> 'row_id');
        v_exercise_definition_id := btrim(p_payload ->> 'exercise_definition_id');
        v_muscle_group_id := btrim(p_payload ->> 'muscle_group_id');
        v_weight := (p_payload ->> 'weight')::double precision;
        v_role := p_payload ->> 'role';
        v_created_at_ms := (p_payload ->> 'created_at_ms')::bigint;
        v_updated_at_ms := (p_payload ->> 'updated_at_ms')::bigint;

        if v_row_id = '' or v_exercise_definition_id = '' or v_muscle_group_id = '' then
          raise exception 'row_id, exercise_definition_id, and muscle_group_id are required for exercise_muscle_mappings attach' using errcode = '22023';
        end if;

        if v_weight <= 0 then
          raise exception 'payload.weight must be > 0 for exercise_muscle_mappings attach' using errcode = '22023';
        end if;

        if v_role is not null and v_role not in ('primary', 'secondary', 'stabilizer') then
          raise exception 'payload.role must be primary|secondary|stabilizer|null for exercise_muscle_mappings attach' using errcode = '22023';
        end if;

        if v_created_at_ms < 0 or v_updated_at_ms < 0 then
          raise exception 'created_at_ms and updated_at_ms must be >= 0' using errcode = '22023';
        end if;

        delete from app_public.exercise_muscle_mappings
          where owner_user_id = p_owner_user_id
            and (
              id = v_row_id
              or (
                exercise_definition_id = v_exercise_definition_id
                and muscle_group_id = v_muscle_group_id
              )
            );

        insert into app_public.exercise_muscle_mappings (
          id,
          owner_user_id,
          exercise_definition_id,
          muscle_group_id,
          weight,
          role,
          created_at,
          updated_at
        )
        values (
          v_row_id,
          p_owner_user_id,
          v_exercise_definition_id,
          v_muscle_group_id,
          v_weight,
          v_role,
          v_created_at_ms,
          v_updated_at_ms
        );
      elsif p_event_type = 'detach' then
        v_exercise_definition_id := btrim(p_payload ->> 'exercise_definition_id');
        v_muscle_group_id := btrim(p_payload ->> 'muscle_group_id');

        if v_exercise_definition_id = '' or v_muscle_group_id = '' then
          raise exception 'exercise_definition_id and muscle_group_id are required for exercise_muscle_mappings detach' using errcode = '22023';
        end if;

        delete from app_public.exercise_muscle_mappings
          where owner_user_id = p_owner_user_id
            and exercise_definition_id = v_exercise_definition_id
            and muscle_group_id = v_muscle_group_id;
      else
        raise exception 'unsupported exercise_muscle_mappings event_type: %', p_event_type using errcode = '22023';
      end if;

    when 'exercise_tag_definitions' then
      if not (p_payload ? 'id') then
        raise exception 'payload.id is required for exercise_tag_definitions events' using errcode = '22023';
      end if;

      v_id := btrim(p_payload ->> 'id');
      if v_id = '' or v_id <> p_entity_id then
        raise exception 'payload.id must match entity_id for exercise_tag_definitions events' using errcode = '22023';
      end if;

      if p_event_type = 'upsert' then
        v_exercise_definition_id := btrim(p_payload ->> 'exercise_definition_id');
        v_name := p_payload ->> 'name';
        v_normalized_name := p_payload ->> 'normalized_name';
        v_deleted_at_ms := (p_payload ->> 'deleted_at_ms')::bigint;
        v_created_at_ms := (p_payload ->> 'created_at_ms')::bigint;
        v_updated_at_ms := (p_payload ->> 'updated_at_ms')::bigint;

        if v_exercise_definition_id = '' then
          raise exception 'payload.exercise_definition_id is required for exercise_tag_definitions upsert' using errcode = '22023';
        end if;

        if length(btrim(v_name)) = 0 or length(btrim(v_normalized_name)) = 0 then
          raise exception 'payload.name and payload.normalized_name are required for exercise_tag_definitions upsert' using errcode = '22023';
        end if;

        if v_created_at_ms < 0 or v_updated_at_ms < 0 or coalesce(v_deleted_at_ms, 0) < 0 then
          raise exception 'exercise_tag_definitions timestamps must be >= 0' using errcode = '22023';
        end if;

        insert into app_public.exercise_tag_definitions (
          id,
          owner_user_id,
          exercise_definition_id,
          name,
          normalized_name,
          deleted_at,
          created_at,
          updated_at
        )
        values (
          v_id,
          p_owner_user_id,
          v_exercise_definition_id,
          v_name,
          v_normalized_name,
          v_deleted_at_ms,
          v_created_at_ms,
          v_updated_at_ms
        )
        on conflict (id, owner_user_id)
        do update
          set exercise_definition_id = excluded.exercise_definition_id,
              name = excluded.name,
              normalized_name = excluded.normalized_name,
              deleted_at = excluded.deleted_at,
              created_at = least(app_public.exercise_tag_definitions.created_at, excluded.created_at),
              updated_at = greatest(app_public.exercise_tag_definitions.updated_at, excluded.updated_at);
      elsif p_event_type = 'delete' then
        v_deleted_at_ms := coalesce((p_payload ->> 'deleted_at_ms')::bigint, p_occurred_at_ms);
        v_updated_at_ms := coalesce((p_payload ->> 'updated_at_ms')::bigint, v_deleted_at_ms);

        update app_public.exercise_tag_definitions
          set deleted_at = v_deleted_at_ms,
              updated_at = greatest(updated_at, v_updated_at_ms)
          where id = v_id
            and owner_user_id = p_owner_user_id;

        get diagnostics v_row_count = row_count;
        if v_row_count = 0 then
          raise exception 'cannot delete missing exercise_tag_definition %', v_id using errcode = 'P0002';
        end if;
      else
        raise exception 'unsupported exercise_tag_definitions event_type: %', p_event_type using errcode = '22023';
      end if;

    when 'session_exercise_tags' then
      if p_event_type = 'attach' then
        v_row_id := btrim(p_payload ->> 'row_id');
        v_session_exercise_id := btrim(p_payload ->> 'session_exercise_id');
        v_exercise_tag_definition_id := btrim(p_payload ->> 'exercise_tag_definition_id');
        v_created_at_ms := (p_payload ->> 'created_at_ms')::bigint;

        if v_row_id = '' or v_session_exercise_id = '' or v_exercise_tag_definition_id = '' then
          raise exception 'row_id, session_exercise_id, and exercise_tag_definition_id are required for session_exercise_tags attach' using errcode = '22023';
        end if;

        if v_created_at_ms < 0 then
          raise exception 'payload.created_at_ms must be >= 0 for session_exercise_tags attach' using errcode = '22023';
        end if;

        delete from app_public.session_exercise_tags
          where owner_user_id = p_owner_user_id
            and (
              id = v_row_id
              or (
                session_exercise_id = v_session_exercise_id
                and exercise_tag_definition_id = v_exercise_tag_definition_id
              )
            );

        insert into app_public.session_exercise_tags (
          id,
          owner_user_id,
          session_exercise_id,
          exercise_tag_definition_id,
          created_at
        )
        values (
          v_row_id,
          p_owner_user_id,
          v_session_exercise_id,
          v_exercise_tag_definition_id,
          v_created_at_ms
        );
      elsif p_event_type = 'detach' then
        v_session_exercise_id := btrim(p_payload ->> 'session_exercise_id');
        v_exercise_tag_definition_id := btrim(p_payload ->> 'exercise_tag_definition_id');

        if v_session_exercise_id = '' or v_exercise_tag_definition_id = '' then
          raise exception 'session_exercise_id and exercise_tag_definition_id are required for session_exercise_tags detach' using errcode = '22023';
        end if;

        delete from app_public.session_exercise_tags
          where owner_user_id = p_owner_user_id
            and session_exercise_id = v_session_exercise_id
            and exercise_tag_definition_id = v_exercise_tag_definition_id;
      else
        raise exception 'unsupported session_exercise_tags event_type: %', p_event_type using errcode = '22023';
      end if;

    else
      raise exception 'unsupported entity_type: %', p_entity_type using errcode = '22023';
  end case;
end;
$$;

-- -----------------------------------------------------------------------------
-- 7. Re-establish privilege grants on the rewritten projection function. The
--    `sync_events_ingest_impl` and `sync_events_ingest` wrappers continue to
--    work unchanged because they delegate via SQL invocation; their function
--    bodies do not embed table OIDs.
-- -----------------------------------------------------------------------------

revoke all on function app_public.sync_apply_projection_event(uuid, text, text, text, bigint, jsonb) from public;
grant execute on function app_public.sync_apply_projection_event(uuid, text, text, text, bigint, jsonb) to authenticated, service_role;

comment on function app_public.sync_apply_projection_event(uuid, text, text, text, bigint, jsonb) is
  'T1 rewrite: dispatch projection events using composite (id, owner_user_id) PK conflict resolution; cross-owner id collisions are impossible by construction.';
